### ISSUE TITLE
Auth integration

### ISSUE THREAD

**Issue by zenhack** [zenhack/sandstorm-hedgedoc#1]
Right now the app unconditionally shows users as guests; we should integrate with sandstorm's identity stuff so we can show people's names, like the older packages for this do.

**Comment by ocdtrekkie** [comment]
Out of curiosity, has the code changed enough to require a novel solution for this, or can we lift what was done in the older packages?

**Comment by zenhack** [comment]
No idea, haven't looked at the way the old package does this yet. Obviously that would be worth investigating.

**Comment by ocdtrekkie** [comment]
https://github.com/PDIS/codimd-sandstorm/commit/cbf3ce131689d44258f920b2093e70a8e92a1fd4 and https://github.com/PDIS/codimd-sandstorm/commit/1fccfa1250da9ed42b79b8359f5a6ac92f0eb3f2 seem to be the key commits to it.

**Comment by zenhack** [comment]
I added a patch adding the plugin, and it doesn't break anything (after tweaking some bit-rotten import paths), but it also doesn't appear to change the behavior at all; everyone still shows as guest. I may poke at this more later, but for now I've pushed an update that just bumps the version to 1.9.2 without including the integration. The WIP `auth-integration` branch has the auth plugin included.

**Comment by zenhack** [comment]
Just pushed 1.9.4-1, which includes the now-working auth plugin. Closing.
